image_settings:
  width: 1920                   # Maks er 3548
  height: 1080                  # Maks er 3552
  offset_x: 814 
  offset_y: 1236
  pixel_format: "bayer_rg8"
  # VÃ¦lg mellem: mono8, mono10, mono10p, mono12p, rgb8, brg8, ycbcr422, 
  # bayer_gr8, bayer_rg8, bayer_gb8, bayer_bg8, 
  # bayer_gr10, bayer_rg10, bayer_gb10, bayer_bg10,
  # bayer_gr10p, bayer_rg10p, bayer_gb10p, bayer_bg10p,
  # bayer_gr12, bayer_rg12, bayer_gb12, bayer_bg12,
  # bayer_gr12p, bayer_rg12p, bayer_gb12p, bayer_bg12p,




video_settings:
  enable_acquisition: "on"     # off or on
  acquisition_fps: 30



lighting_settings:
  exposure_time: 15000.0        # mikrosekunder 
  gain: 1.0



auto_settings:
  auto_brightness_target: 0.5   # Mellem 0.0 og 1.0
  auto_function: "min_gain"     # "min_gain", eller "min_exposure"

  auto_exposure: "continuous"   # off, once, continuous
  auto_exposure_lower_limit: 1.0
  auto_exposure_upper_limit: 100000.0

  auto_gain: "continuous"       # off, once, continuous
  auto_gain_lower_limit: 0
  auto_gain_upper_limit: 24